# Generated by Django 4.0.4 on 2022-05-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=30, null=True)),
                ('product_name', models.CharField(max_length=30, null=True)),
                ('descr', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
