# Generated by Django 4.0.4 on 2022-05-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='descr',
            field=models.TextField(null=True),
        ),
    ]
